# Para esta Tarea

Generar un archivo tipo Notebook de Python que contenga el código fuente de varios ejercicios aplicados a los conceptos vistos:

Importar el archivo “supermarket_sales.csv”

Importar la librería NumPy. Generar estadística descriptiva básica en las columnas unit_price y quantity: Cálculo de la media, mediana, moda

Obtener el ticket promedio:

1) por ciudad,

2) por product line y ciudad,

3) por género,

4) por género y product line

Usar el método rank para generar top 5 de:

1) ventas por ciudad,

2) ventas por member,

3) ventas por payment. Obtener además el % de aporte de cada categoría. 

P.ej. La ciudad X aporta con el 25% del total de ventas, etc.

Cálculo de una matriz de correlación entre la hora (sin minutos) y el total, y otra que correlacione el unit_price con el rating de la transacción, para validar si los productos más caros son los que dejan más margen

# Importacion de librerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Desarrollo

## Lectura del archivo

In [4]:
df = pd.read_csv('../../Archivos-Analisis/files-tarea-m35/supermarket_sales.csv')
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [5]:
df.sample(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
242,142-72-4741,C,Naypyitaw,Member,Male,Fashion accessories,93.20,2,9.3200,195.7200,2/28/2019,18:37,Credit card,186.40,4.761905,9.3200,6.0
984,189-40-5216,C,Naypyitaw,Normal,Male,Electronic accessories,96.37,7,33.7295,708.3195,1/9/2019,11:40,Cash,674.59,4.761905,33.7295,6.0
977,518-71-6847,B,Mandalay,Member,Male,Food and beverages,26.60,6,7.9800,167.5800,2/26/2019,15:10,Ewallet,159.60,4.761905,7.9800,4.9
934,501-61-1753,B,Mandalay,Normal,Female,Home and lifestyle,63.15,6,18.9450,397.8450,1/3/2019,20:24,Ewallet,378.90,4.761905,18.9450,9.8
557,283-26-5248,C,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,20:23,Ewallet,985.20,4.761905,49.2600,4.5

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [8]:
df.dtypes

Invoice ID                  object
Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [15]:
df.describe().round(2)

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00
mean,55.67,5.51,15.38,322.97,307.59,4.76,15.38,6.97
std,26.49,2.92,11.71,245.89,234.18,0.00,11.71,1.72
min,10.08,1.00,0.51,10.68,10.17,4.76,0.51,4.00
25%,32.88,3.00,5.92,124.42,118.50,4.76,5.92,5.50
50%,55.23,5.00,12.09,253.85,241.76,4.76,12.09,7.00
75%,77.94,8.00,22.45,471.35,448.90,4.76,22.45,8.50
max,99.96,10.00,49.65,1042.65,993.00,4.76,49.65,10.00

## Deteccion de nulos

In [9]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

## Masajeo de datos
Conversion de los tipos de datos object a string

In [11]:
# Convertir todas las columnas de tipo object a string
obj_columns = df.select_dtypes(include='object').columns
df[obj_columns] = df[obj_columns].astype('string')

df.dtypes

Invoice ID                 string[python]
Branch                     string[python]
City                       string[python]
Customer type              string[python]
Gender                     string[python]
Product line               string[python]
Unit price                        float64
Quantity                            int64
Tax 5%                            float64
Total                             float64
Date                       string[python]
Time                       string[python]
Payment                    string[python]
cogs                              float64
gross margin percentage           float64
gross income                      float64
Rating                            float64
dtype: object

## Analisis

In [22]:
# Estadistica descriptiva de la columna unit price
unit_price_mean = df['Unit price'].mean()
unit_price_median = df['Unit price'].median()
unit_price_moda = df['Unit price'].mode()

print('Estadística descriptiva de la columna Precio Unitario:')
print(f'La media del Precio Unitario es de: {unit_price_mean:.2f}')
print(f'La mediana del Precio Unitario es de: {unit_price_median:.2f}')
print(f'La moda del Precio Unitario es de: {unit_price_moda[0]:.2f}')

Estadística descriptiva de la columna Precio Unitario:
La media del Precio Unitario es de: 55.67
La mediana del Precio Unitario es de: 55.23
La moda del Precio Unitario es de: 83.77

In [23]:
# Estadistica descriptiva de la columna quantity
quantity_mean = df['Quantity'].mean()
quantity_median = df['Quantity'].median()
quantity_moda = df['Quantity'].mode()

print('Estadística descriptiva de la columna Cantidad:')
print(f'La media de la Cantidad es: {quantity_mean:.2f}')
print(f'La mediana de la Cantidad es: {quantity_median:.2f}')
print(f'La moda de la Cantidad es: {quantity_moda[0]:.2f}')

Estadística descriptiva de la columna Cantidad:
La media de la Cantidad es: 5.51
La mediana de la Cantidad es: 5.00
La moda de la Cantidad es: 10.00

## Obtencion del ticket promedio
1) por ciudad,
2) por product line y ciudad,
3) por género,
4) por género y product line

## Usar el método rank para generar top 5 de:
1) ventas por ciudad,
2) ventas por member,
3) ventas por payment. Obtener además el % de aporte de cada categoría.  (P.ej. La ciudad X aporta con el 25% del total de ventas, etc.)

## Matriz Correlacional
Cálculo de una matriz de correlación entre la hora (sin minutos) y el total, y otra que correlacione el unit_price con el rating de la transacción, para validar si los productos más caros son los que dejan más margen

# DataFrame de referencia

In [18]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6